version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=lambda,dynamodb
      - DEBUG=1
    volumes:
      - "./localstack:/tmp/localstack"
      - "./setup-localstack.sh:/docker-entrypoint-initaws.d/setup-localstack.sh"